version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  test:
    working_directory: ~/argo-api
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}

      - run:
          name: install dependencies
          command: |
            sudo npm i -g  codecov node-gyp
            npm i
      - run:
          name: test
          command: npm test && codecov

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

workflows:
  build-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          region: AWS_REGION_DEV
          account-url: AWS_ECR_ACCOUNT_URL_DEV
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          name: aws-ecr-build-push-dev
          repo: hosting-api
          tag: dev
          extra-build-args: --build-arg CODE_VERSION=${CIRCLE_SHA1:0:7}
          requires:
            - test
          filters:
            branches:
              only: dev
      - aws-ecr/build-and-push-image:
          region: AWS_REGION_PROD
          account-url: AWS_ECR_ACCOUNT_URL_PROD
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          name: aws-ecr-build-push-prod
          repo: hosting-api
          tag: prod
          extra-build-args: --build-arg CODE_VERSION=${CIRCLE_SHA1:0:7}
          requires:
            - test
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          cluster-name: "hosting-api-dev"
          container-image-name-updates: "container=hosting-api-dev-api,tag=dev"
          family: "hosting-api-dev-api"
          aws-region: AWS_DEFAULT_REGION_DEV
          requires:
            - aws-ecr-build-push-dev
          filters:
            branches:
              only: dev
      - aws-ecs/deploy-service-update:
          cluster-name: "hosting-api-prod"
          container-image-name-updates: "container=hosting-api-prod-api,tag=prod"
          family: "hosting-api-prod-api"
          aws-region: AWS_DEFAULT_REGION_PROD
          requires:
            - aws-ecr-build-push-prod
          filters:
            branches:
              only: master
