version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.1
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
  build-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          name: push-dev-image
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          repo: hosting-api
          tag: dev
          extra-build-args: --build-arg CODE_VERSION=${CIRCLE_SHA1:0:7}
          filters:
            branches:
              only: dev
      - aws-ecs/deploy-service-update:
          cluster-name: 'hosting-api-dev'
          container-image-name-updates: 'container=hosting-api-dev-api,tag=dev'
          family: 'hosting-api-dev-api'
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: dev
