version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.1
  aws-cli: circleci/aws-cli@1.3

jobs:
  deploy-dev:
    working_directory: ~/argo-api
    docker:
      - image: circleci/python:3.6.4
    environment:
      AWS_PAGER: ''
    steps:
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: Deploy API Service
          command: aws ecs update-service --force-new-deployment --cluster  hosting-api-dev  --service hosting-api-dev-api

workflows:
  build-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          name: push-dev-image
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          repo: hosting-api
          tag: dev
          extra-build-args: --build-arg CODE_VERSION=${CIRCLE_SHA1:0:7}
          filters:
            branches:
              only: dev
      - deploy-dev:
          requires:
            - push-dev-image
          filters:
            branches:
              only: dev
